### ISSUE TITLE
Update the Contact Us page

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/oasis-new-website#100]
Contact us from the footer goes to https://www.oasis-open.org/org/offices/

This lists multiple emails, e.g. info@, dataprivacy@, etc. Also lists the current Corporate Drive address as well as the new one. Should bring this up to date, especially checking existing emails listed and adding new ones as they are needed

**Comment by chet-ensign** [comment]
We discussed today. @CarolGeyer noted that this is done. Closing this ticket.
