### ISSUE TITLE
Search box not available on kws pages

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#105]
The site has a search form on the top right side of the page. 
But,  when you log on to the TC member pages,  it is no longer there.   
Could the template be modified to have it also on the kws part of the site?

**Comment by chet-ensign** [comment]
Pim, the current TC member pages are simply restyled versions of the old ones. I will ask Scott, but I don't believe we have a way to put a search box on those pages now.

**Comment by chet-ensign** [comment]
We discussed this today (Guy, Scott, Carol, Chet). We noted that the TC member pages didn't have search boxes in the past. As that is not under our control, we don't think this will be possible until we migrate the committee pages to a new platform. We'll close this for now.
