### ISSUE TITLE
Document Retention Policy lost formatting

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#110]
This was HM #251. See https://www.oasis-open.org/policies-guidelines/document-retention-destruction/

Looks like this will be an OASIS fix. Other policies may need this fix as well.

**Comment by OASIS-OP-Admin** [comment]
Reformatted the page. The block of documents and the retention requirements had to be cut & pasted into a table. All complete now so I will close this ticket.
