### ISSUE TITLE
Event calendar date, time, display - inconsistency

### ISSUE THREAD

**Issue by jane-harnad** [oasis-dev/oasis-new-website#112]
On the event calendar -- Is there a reason why the date/time display is different for -- "The EU Open Source Policy Summit 2021."  **Friday, 5 Feb 2021 at 9:17 am EST  vs. 5 Feb 2021**

**Comment by chet-ensign** [comment]
HM is working on this. It requires a style sheet tweak.

**Comment by jane-harnad** [comment]
After further review -- the issue we have is with the single date events that include a time. The time seems to get lost in the current format. Is there a better font and/or layout option available? Using all caps or a divider might help example: "Friday, 5 Feb   |   11:00 AM EST"  or FRIDAY, 5 FEB — 11:00 AM EST".

**Comment by OASIS-OP-Admin** [comment]
HumanMade ticket https://app.zenhub.com/workspaces/oasis-design--build-5f1f650945622c000fb4d09c/issues/humanmade/oasis/286 opened to track this update

**Comment by OASIS-OP-Admin** [comment]
HM fixed this. Dates and times are consistent now. 

Closing this ticket.
