### ISSUE TITLE
Fix link for "Member or Observer" on How to Join a Committee page

### ISSUE THREAD

**Issue by mbminto** [oasis-dev/oasis-new-website#113]
The link for "Member or Observer" in #3 below doesn't work. Clicking on it results in a page that says nothing found / page not found. 

https://www.oasis-open.org/join/

How to Join a Committee
If you are a member of OASIS and already have a user account in the OASIS member database:
1. Go to All Groups (your OASIS username and password are required) and choose a Committee from the Available Groups list.
2. Select the “Join Group” link.
3. You will have the option to join as a **Member or Observer**. (this is the link: http://www.oasis-open.org/committees/roles.php)

**Comment by OASIS-OP-Admin** [comment]
Thanks for the report, Mary Beth. I'll sort this out.

**Comment by chet-ensign** [comment]
@mbminto  - Fixed the link to https://www.oasis-open.org/roles/. The color and weight of the dots isn't quite as heavy but the content looks correct.
