### ISSUE TITLE
Covid page disappeared

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#114]
On 27 May 2020 we posted a news item "How OASIS work can help fight COVID-19" that points to the following page:

https://www.oasis-open.org/covid

This now returns:

Nothing Found
Sorry, it seems we can't find what you're looking for.
Maybe you'd like to return to the homepage?

**Comment by chet-ensign** [comment]
Scott is investigating. Seems to be a bug. The page content is there but for some reason doesn't show up when published.

**Comment by chet-ensign** [comment]
@scottmcgrath fixed the problem. New link is now up for EU Foundation. I'll close this ticket.
