### ISSUE TITLE
Create a historical policies page for the really old versions

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#115]
This came up in considering whether to increase the limit of 5 historic documents to accommodate the list for the TC Process. It as 18 historical copies. That would make the page busy for little benefit. 

@scottmcgrath suggested instead going with a historic policies page where the older ones could be listed. This ticket is to try that out.

**Comment by OASIS-OP-Admin** [comment]
HM solved this instead by adding a more... button. Last 5 historical policies will be displayed and then the button. Clicking it pulls up all the policies. Checked it out and it works fine. I'll go ahead and close this ticket.
