### ISSUE TITLE
OASIS EU site,  Menu option does not work on mobile

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#119]
On the mobile version of https://www.oasis-open.eu/,  the "Menu" button does not work.  No menu appears when the button is pressed.

Tested with Chrome, Brave and Opera on Android and the stock browser on SailfishOS.

**Comment by OASIS-OP-Admin** [comment]
@scottmcgrath @PimvanderEijk - I see that too. It isn't clear though what that hamburger button should do when clicked. It doesn't have a counterpart on the web site. Perhaps it should just come off for now?

**Comment by PimvanderEijk** [comment]
This menu button should open access to a list with items "About",  "News items",  "OASIS Open",  just like the corresponding button on the mobile version of the OASIS dot org site.

**Comment by chet-ensign** [comment]
Opened HumanMade issue https://github.com/humanmade/OASIS/issues/288 to report this. Will follow up when maintenance begins in April.

**Comment by OASIS-OP-Admin** [comment]
HM fixed this problem and I confirmed on production. Closing the ticket.
