### ISSUE TITLE
Link to TC Administration Homepage does not work

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#121]
After logging in to Kavi,  you are at https://www.oasis-open.org/kws

Below at the right there is a link to "TC Administration Homepage" with URL http://www.oasis-open.org/resources/tcadmin. 

This link returns a "Nothing Found" error page.

**Comment by PimvanderEijk** [comment]
If I type http://www.oasis-open.org/resources/tc-admin, there seems to be a re-direct to:

https://www.oasis-open.org/tc-admin-request-checklist/

That's another "Nothing Found".

**Comment by PimvanderEijk** [comment]
OK now found the page at https://www.oasis-open.org/member-resources/.

**Comment by OASIS-OP-Admin** [comment]
Right - member-resources is to become the replacement for the TC Admin page. 

I'll go ahead and close this ticket.
