### ISSUE TITLE
Bad content at https://www.oasis-open.org/resources/

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#122]
This page includes the following as readable text:

[mk_page_section bg_image=”https://www.oasis-open.org/wp-content/uploads/2018/02/52588.jpg” bg_position=”center center” bg_stretch=”true” video_color_mask=”rgba(0,0,0,0.47)” video_opacity=”1″ padding_top=”90″ padding_bottom=”90″ sidebar=”sidebar-1″][vc_column][vc_column_text css=”.vc_custom_1517876259739{margin-bottom: 0px !important;}”]

**Comment by OASIS-OP-Admin** [comment]
@scottmcgrath - Scott, should we take this page down? It looks like a page we didn't intend to carry over. There are no links to it from the homepage. 

@PimvanderEijk - how did you get to it? Did you come across a link?

**Comment by PimvanderEijk** [comment]
I found it trying to find another page by guessing URLs (see other issue). It is not linked to from somewhere.

**Comment by OASIS-OP-Admin** [comment]
I renamed the file 'obsolete-resoures' to ensure no one stumbles across it. I'll close this ticket.
