### ISSUE TITLE
Image size on event calendar

### ISSUE THREAD

**Issue by jane-harnad** [oasis-dev/oasis-new-website#123]
Is there a way to increase the size of the logo area on our event calendar? (Space to the right of each event description.) I am finding it extremely difficult to locate event images to fit the tiny space provided. Most event banners provided by organizers don't fit -- so I'm left with trying to find alternative images.

**Comment by OASIS-OP-Admin** [comment]
@jane-harnad - Do you just need a larger size or do you need several optional box sizes for images that you can use for the announcements? 

This will take HM redesigning the layout of the post or post(s), so we should get our request organized in advance.

**Comment by OASIS-OP-Admin** [comment]
Sent email to ask Jane if this is still a problem. Jane confirms that it is.

**Comment by chet-ensign** [comment]
Increased image box has been rolled into production. See https://www.oasis-open.org/events/

I will close this ticket. @jane-harnad @jharnad - you can reopen if you see need for more work.
