### ISSUE TITLE
Change button text on  from "Join this TC/SC" to "How to join"

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/oasis-new-website#124]
The button text is misleading and causes confusion.

Member Ger Clancy emailed asking why he was having trouble joining a UBL subcommittee. From the UBL members-only page, he clicked the link for the SC. Once he got there, he clicked the Join this SC button but kept winding up at an instructions page. 

The problem was that the link took him to the *public* SC page. He needed to click the SC members page button first. 

Granted this is the first time anyone has brought this to my attention but I can see how the current label on the button is misleading. If we change it to 'how to join' that will be a clearer indication of what the button really does.

**Comment by chet-ensign** [comment]
The button text is a Kavi feature, not under our control. Because we only know that this happened this one time and because we likely cannot change it easily, I'm closing this ticket with no action. If it occurs again, we'll try to work with Kavi support to change the text.
