### ISSUE TITLE
Links to docs.oasis-open.org should use https: instead of http:

### ISSUE THREAD

**Issue by paul-knight** [oasis-dev/oasis-new-website#125]
Two links from https://www.oasis-open.org/policies-guidelines/ should be modified to use https:

- Directives for Filenames, URIs, Namespaces, and Metadata 
-- currently http://docs.oasis-open.org/specGuidelines/ndr/namingDirectives.html

- Guidelines to Writing Conformance Clauses
-- http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html

**Comment by OASIS-OP-Admin** [comment]
Updated both links to https. Closing the ticket.
