### ISSUE TITLE
Link to TC Public Page of LegalXML MS doesn't work

### ISSUE THREAD

**Issue by mbminto** [oasis-dev/oasis-new-website#126]
https://www.oasis-open.org/apps/org/workgroup/legalxml-ms/ 
If you go to the site above and click on TC Public Page, the message says "Nothing Found."

**Comment by chet-ensign** [comment]
This has been fixed. Now goes to the MS page on the legacy site. (We didn't migrate Member Sections to new site.) 

Closing this ticket.
