### ISSUE TITLE
Link to join page not working

### ISSUE THREAD

**Issue by PimvanderEijk** [oasis-dev/oasis-new-website#130]
When I click on the blue cross above "A community for everyone"

![image](https://user-images.githubusercontent.com/8939497/116006835-422d9000-a60d-11eb-8658-e9c98289f79d.png)

I end up at https://www.oasis-open.org/join-3/. 

![image](https://user-images.githubusercontent.com/8939497/116006882-6d17e400-a60d-11eb-8792-dba35aa14ff2.png)

**Comment by OASIS-OP-Admin** [comment]
It looks like someone changed the file name from join-3 to join. Corrected the link and now it is working correctly.
