### ISSUE TITLE
Press release did not migrate to new web site 

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/oasis-new-website#132]
Mary Beth discovered that the press release https://www-legacy.oasis-open.org/news/pr/oslc-approves-five-open-source-specifications-for-integrating-software-lifecycle-tools did not migrate to the new website. The original link was https://www.oasis-open.org/news/pr/oslc-approves-five-open-source-specifications-for-integrating-software-lifecycle-tools. However, I cannot find it on the new website either by searching all news entries or by paging back through all the press releases.

**Comment by chet-ensign** [comment]
I recreated the press release so the link works now. I'll close the ticket.
