### ISSUE TITLE
Individual Membership: fix bulleted list 

### ISSUE THREAD

**Issue by mbminto** [oasis-dev/oasis-new-website#139]
Quick fix needed on the bulleted list found under the ["Personal Membership" -> Individual Membership section](https://www.oasis-open.org/join/):

You may apply for a personal “Individual” membership if you:

- are self-employed or unemployed and
- sign the **OASIS Mem**https://www.oasis-open.org/policies-guidelines/
- **bership Agreement** on your own behalf and
- are legally able to directly license your Intellectual Property (i.e., you haven’t assigned your IPR to an employer or other entity).

**Comment by OASIS-OP-Admin** [comment]
Thanks for catching that, Mary Beth. All fixed  now.
