### ISSUE TITLE
Link US-TAG pages from the Projects page 

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#14]
Issue reported by Dee Schur. 

I found two links the are not connected to old website content: https://www.oasis-open.org/ustag-iso317-consumer-privacy-by-design/ and https://www.oasis-open.org/ustag-iso324-sharing-economy. 

Chet notes that these may belong as entries on the Projects page. Need to confirm with Dee.  
<DS> Scott has fixed both US TAG pages they now link to the correct content but the logos are not properly sized.

**Comment by scottmcgrath** [comment]
I have fixed page https://www.oasis-open.org/us-tag-sharingeconomy/  .  The page renders, but not anywhere in nav

I cannot find a WP page or the original content on the legacy site for /ustag-iso324-sharing-economy.

**Comment by chet-ensign** [comment]
@scottmcgrath - Carol was talking about adding them to the Projects page. For the moment though, the TAG program is listed in the footer - see https://www.oasis-open.org/tags/

**Comment by chet-ensign** [comment]
Also, those logos are gi-normous.

**Comment by scottmcgrath** [comment]
Dee later suggested the othe page she was looking for is https://www.oasis-open.org/ustag-iso317-consumer-privacy-by-design/
I fixed the post on that too.  I made minor edits to logo sizes on both 
 https://www.oasis-open.org/us-tag-sharingeconomy/  and
https://www.oasis-open.org/ustag-iso317-consumer-privacy-by-design/

Both pages require redesign

**Comment by scottmcgrath** [comment]
https://www.oasis-open.org/ustag-iso324-sharing-economy.  remains missing

**Comment by chet-ensign** [comment]
It looks to me like /us-tag-sharingeconomy/ and /ustag-iso324-sharing-economy/ are two filenames for the same animal. They were listed from https://www-legacy.oasis-open.org/tags which was under the Groups drop down.

I suggest we don't worry about the second one since the first is the one that was linked from the legacy site.

**Comment by chet-ensign** [comment]
I think I can fix them on the ANSI TAG page.

**Comment by chet-ensign** [comment]
Since I'm there already.

**Comment by chet-ensign** [comment]
I went ahead and updated the links on https://www.oasis-open.org/tags/ using /us-tag-sharingeconomy/. I don't know that we ever had the ustag-iso317

**Comment by CarolGeyer** [comment]
I added Project entries for each of our 3 TAGs.

**Comment by chet-ensign** [comment]
They look good! I think we can close this ticket.
