### ISSUE TITLE
Fix the formatting of the Benefits Matrix page

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#27]
The Benefits Matrix at https://www.oasis-open.org/join/benefits-matrix/ is poorly formatted and difficult to read. Should be edited and cleaned up.

**Comment by chet-ensign** [comment]
@CarolGeyer looks like you took care of this one. Can i go ahead and close it? It looks quite finished now.

**Comment by CarolGeyer** [comment]
I've made some improvements, but there are still some instances where the text size and column widths need to be adjusted. This table uses the "Classic WP Editor", and I can't figure out how to do the necessary fixes.

**Comment by chet-ensign** [comment]
Carol, can you tell me what you want to fix? I assume changing the column widths so that Contributor doesn't wrap. Anything else?

**Comment by chet-ensign** [comment]
@CarolGeyer - can you tell me what needs to be fixed?  I assume changing the column widths so that Contributor doesn't wrap. Anything else?

**Comment by chet-ensign** [comment]
We discussed and agreed that this page is acceptable now. Closing this ticket.
