### ISSUE TITLE
Photos too large on News posts

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#29]
The images we use for News posts (Press releases, Project news) look great on the homepage and News frontpage, but they display much too large on the individual pages:

Examples:
https://www.oasis-open.org/2020/11/02/invitation-to-comment-on-exchange-header-envelope-xhe-v1-0-from-the-bdxr-tc-end-0/

https://www.oasis-open.org/2020/11/09/accenture-splunk-and-others-back-baseline-protocol-for-public-blockchains/

**Comment by chet-ensign** [comment]
Carol, have a look at the second one. I scaled the image down. I can adjust the size as you like - still looks OK on the main page.

**Comment by chet-ensign** [comment]
Discussed on sprint planning call on 11/16/2020. Joleen is going to try setting up WP to crop images to the correct size. We can then adjust as needed.

**Comment by chet-ensign** [comment]
HM addressed this in sprint 6. Featured images need some new cropped sizes (#215). It looks correct to me. @CarolGeyer, can you check and confirm?
