### ISSUE TITLE
Mail list archive display has lots of HTML cruft above the list of monthly archives

### ISSUE THREAD

**Issue by paul-knight** [oasis-dev/oasis-new-website#30]
Example: https://lists.oasis-open.org/archives/openc2/

If you scroll way down the page, you eventually come to the desired archive monthly listings.

**Comment by chet-ensign** [comment]
This looks like another instance of style sheets not being applied on the Kavi side. I emailed the description to Jesse at Bitlancer.

**Comment by chet-ensign** [comment]
Jesse notified us that the fix has to be done on the Kavi side. He's opening a ticket with them.

**Comment by chet-ensign** [comment]
Jesse has opened a ticket with Higher Logic to update the stylesheet on their server.

**Comment by chet-ensign** [comment]
Part way there. Higher Logic applied the style sheet but there are still broken elements on the page. Notified Jesse.

**Comment by chet-ensign** [comment]
Just noting that Jesse continues the back and forth with Higher Logic's help desk without success.

**Comment by OASIS-OP-Admin** [comment]
Believe it or not, Jesse is still going back and forth with Kavi tech support. It appears to be beyond the capacity of their engineers to resolve.

**Comment by OASIS-OP-Admin** [comment]
Jesse and HM finally got this working. The mail list archives are back to normal. Closing the ticket.

**Comment by paul-knight** [comment]
Minor item: In the mail list display, the link to "OASIS Mailing Lists Help" is broken - needs to point to www-legacy, or the target should be created on new www.
