### ISSUE TITLE
Crop for full-width images

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#31]
We need a ratio option added for images that appear full width on the top of main pages, to match the wireframe design. Currently the only options are too large. (Carol noted this on Slack and HM said another option was needed.)

**Comment by chet-ensign** [comment]
This appears to match https://github.com/humanmade/OASIS/issues/193 - Add ability to have full-width featured image on pages. We've prioritized this to address in the next sprint.

**Comment by chet-ensign** [comment]
Discussed on 11/13. Agreed that we should prioritize this for next round of development.

**Comment by chet-ensign** [comment]
See update for #29

**Comment by chet-ensign** [comment]
HM addressed this issue in sprint 6, Featured images need some new cropped sizes (#215) and Add ability to have full-width featured image on pages (#193). @CarolGeyer, can you take a look at the Projects page and the Open Projects Program page and confirm that they meet your requirement?
