### ISSUE TITLE
Reduce size of video block

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#33]
The video block's currently fixed column width is too large.

Example: https://www.oasis-open.org/open-projects/

**Comment by chet-ensign** [comment]
Opened as https://github.com/humanmade/OASIS/issues/228 for HM

**Comment by chet-ensign** [comment]
Discussed on sprint planning call 11/16/2020. Joleen asking for more info. Looks like the video is set to the column width. Only thing that looks off to her are the top and bottom black bars which are a Youtube feature and not under our control. 

Scott will discuss w/ Carol and refine directions to HM.
