### ISSUE TITLE
Links in Membership Agreement are broken 

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#34]
This was reported by @guywmartin. Ani interested member noted that the following links in the MA section 2 are broken: 

* http://www.oasis-open.org/who/intellectualproperty.php
* https://www.oasis-open.org/who/boardpolicies.php

These should both go to the policies page and, indeed, on the legacy site, they redirect there. 

Not sure who has control over the MA or whether we can fix the redirect from here. @scottmcgrath, any thoughts?

**Comment by scottmcgrath** [comment]
also missing  http://www.oasis-open.org/who/contactus.php  which appears later in MA.

I will fix the redirect on these, as they are links named in the 2005 MA form and were previously redirected.  when we rewrite the MA, we should point to the current links directly.

**Comment by chet-ensign** [comment]
Thanks Scott.

**Comment by scottmcgrath** [comment]
fixed
