### ISSUE TITLE
Edit text in panel above footer

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#38]
Change "The work of OASIS is supported by organizations from around the world. Membership levels include Foundational Sponsors, Sponsors, and Contributors." to "The work of OASIS is supported by organizations from around the world. Members include:"

**Comment by chet-ensign** [comment]
Looks like this may be part of the footer. I don't know whether we can make this edit directly.

**Comment by chet-ensign** [comment]
Discussed on 11/13. We want this eventually but agree that it is not a priority for now.

**Comment by chet-ensign** [comment]
Guy says let's go ahead and make the changes  to (a) the wording as laid out  above and (b) the OP sponsors on the rotating banner.

**Comment by chet-ensign** [comment]
I edited the sponsor block as @CarolGeyer requested. It is not yet showing up on the site. Perhaps there's time needed for WP to sync.

**Comment by chet-ensign** [comment]
Scott flushed the WP cache. The changed text is now displayed. I'm closing this ticket.
