### ISSUE TITLE
On Open Matters page, reverse order of events, add headshot of guest

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#39]
Suggestion from Jason K.  "on the Open Matters page, I think they should be sorted reverse (most recent at the top...) also it would be nice to have a  preview images of the guest instead of it just saying "episode" (could take this from youtube screen grab)"

This is for https://www.oasis-open.org/open-matters-forum

This is a page we directly edit so totally in our control

**Comment by chet-ensign** [comment]
I take back my previous comment. The contents on the page are fed from the events collection, so it will probably sort same order - oldest to newest. I added a comment on this to HM ticket https://github.com/humanmade/OASIS/issues/259

**Comment by CarolGeyer** [comment]
If this is the same issue as #56, we can close this one.
