### ISSUE TITLE
Update table block styles to match the design

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#46]
This is HM issue #35, in their Backlog column. Do we think we need more table styling options? 
Goal
As a visitor, I want to see well-designed tables, so that I can easily understand information published by OASIS.

Details
Tables are a key element for OASIS, used on a lot of pages in a lot of different ways. It's important that these tables are well-formatted and well-designed, and can be easily added (and customized?) within the block editor.

Notes
Question: Should tables be customizable in some way? Perhaps more than one format for the Gutenberg block? The default block provides customization options plus 2 styles already, and we can style them to match the design.
Designs / Screenshots
https://projects.invisionapp.com/share/HQYR0R6NWYE#/screens/431731749

Proposed Tactic
Style the default regular and striped table options to match the designs.

**Comment by chet-ensign** [comment]
Discussed this at 11/24/2020 meeting. Carol/Guy consider this important. Check w/ Furthermore on designs.

**Comment by CarolGeyer** [comment]
Can we combine with with issue #92? We have an immediate need to get the tables to adjust the width of tables, so they match the body text and not appear at full page width. This is an issue on https://www.oasis-open.org/join-3/ and https://www.oasis-open.org/foundation-as-a-service/

**Comment by OASIS-OP-Admin** [comment]
@CarolGeyer I will edit issue #92 to capture this need and make sure the issue is queued up to discuss with HM on Friday. We don't have a retainer arrangement with FurtherMore so I don't know that there is budget to get any of their time. But this is a concrete need that HM can address through style sheets.

**Comment by OASIS-OP-Admin** [comment]
i opened https://app.zenhub.com/workspaces/oasis-design--build-5f1f650945622c000fb4d09c/issues/humanmade/oasis/247 to raise this with HM

**Comment by chet-ensign** [comment]
This issue is closed on HM (#247). I will close here as well.
