### ISSUE TITLE
Install ShareThis plugin

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#48]
This is HM issue #34, in their Backlog column. It is labelled Should do

Goal
As a visitor, I want to be able to easily share content to social media, so that I can tell others about OASIS.

Details
Sharing on the site to the most common social media platform (Twitter, Facebook, LinkedIn) should be easy and integrated into the site.

Notes
Open questions:

What platforms should be enabled? Twitter, Facebook, LinkedIn, others?
Should there be other ways to share, e.g. email, RSS?

**Comment by CarolGeyer** [comment]
Share platforms I see commonly are LinkedIn, Twitter, Facebook, and Email. All those would be great. If we have to choose, LinkedIn and Twitter are top.

**Comment by chet-ensign** [comment]
Joeleen reports that the ShareThis plugin is installed on staging. I checked and it is running there. I'll close this ticket.

**Comment by chet-ensign** [comment]
I confirmed that it works. Easy to configure.
