### ISSUE TITLE
Archive link is missing at the end of the event calendar

### ISSUE THREAD

**Issue by jane-harnad** [oasis-dev/oasis-new-website#49]
A new category called 'open matters' was added, but doesn't appear in the event type search option. Can someone look into it? Also, the archive link is missing (at the end of the calendar).

**Comment by chet-ensign** [comment]
I just checked this and edited the description. The link to View event archive is at the bottom of the page. However, clicking it does not take you to an archive. It simply jumps you to the top of the page.

**Comment by scottmcgrath** [comment]
The link is supposed to go to https://www.oasis-open.org/presentations/  
I have fixed the link.
noting here, though it may never be seen again - how I found the events page that is used as the events "archive" --IN THIS CONTEXT archive page means the rollup page of all the posts.  In Dashboard/Settings/Reading I found the name of the archive page.  I fixed the link on that page.  For reasons unknown, the archive page in dashboard looks nothing like the actual page after it is built.
