### ISSUE TITLE
Build the ticketing system, revised to support OPs as well as TCs, on the new website

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#51]
The current ticketing system lives at https://www-legacy.oasis-open.org/resources/tc-admin-requests. It needs to be rebuilt on the new website and enhanced to support both Open Projects and TCs, before the legacy system can be shut down.

**Comment by chet-ensign** [comment]
Experimenting with Gravity Forms and with JIRA issue templates. odd problem with Gravity Forms. I created a simple form (https://www.oasis-open.org/wp-admin/admin.php?page=gf_edit_forms&id=2) with a handful of fields. Very generic. However, when I place it on a page, the input fields are squashed between the text above and below (https://www.oasis-open.org/gravity-forms-test-page/). I took their simple contact-us form (https://www.oasis-open.org/wp-admin/admin.php?page=gf_edit_forms&id=1) and put it on a page and it displayed just fine. However, I cannot find any difference between the settings on that form and the form I have created. Any ideas on how to fix this would be appreciated. Searching in the knowledge base and the web is not bringing up anything revealing.

put question to HM in Slack

**Comment by chet-ensign** [comment]
After HumanMade updating forms style sheets, the test form displayed correctly and sent notifications, opened a TC Admin JIRA issue. We'll proceed with planning the transition.

**Comment by OASIS-OP-Admin** [comment]
Paul is reviewing the current support forms on the legacy website. Editing the ticket content. Need to review list for any new tickets needed. Need to review forms procedure on WP

**Comment by OASIS-OP-Admin** [comment]
Revised all tickets to work for both TC and OP outputs. Recreated all support request forms in Gravity Forms and made active on website. Much easier to work with Gravity Forms. 

The work is complete so I am closing this ticket.
