### ISSUE TITLE
Events page sort by date seems wrong for past events

### ISSUE THREAD

**Issue by scottmcgrath** [oasis-dev/oasis-new-website#53]
I see the event page default shows upcoming event in chronological order - most current to most future events.  That seems right.   BUT, when looking at the calendar of past events, using the same chronological order puts the oldest event on top and the most recently ended events at the bottom - of a list thta will get very long over time.  

Can the Past events filter switch the event ordering to reverse chronological?

**Comment by chet-ensign** [comment]
Add to next HM Sprint

**Comment by OASIS-OP-Admin** [comment]
HumanMade switched the order. The events now display from most recent backwards. Closing this ticket.
