### ISSUE TITLE
Yellow Alert Banner (with COVID) currently doesn't go anywhere

### ISSUE THREAD

**Issue by guywmartin** [oasis-dev/oasis-new-website#62]
The first time you visit the new site, the yellow 'COVID information' banner shows up, and clicking on it just refreshes the home page - it should go to this page: https://www.oasis-open.org/covid/ (that page currently gives a 404 - but I think we migrated the content somewhere).

We should disable this banner for now, and also fix/link the COVID page back in.

**Comment by chet-ensign** [comment]
Either link it properly or disable it.

**Comment by scottmcgrath** [comment]
How to fix/edit/update announcement block instructions are detailed in HM issues - simple story - edit homepage - using announcement block style.

I've updated the announcement to encourage registration for awards ceremony.
