### ISSUE TITLE
Add in link to OASIS SWAG store

### ISSUE THREAD

**Issue by guywmartin** [oasis-dev/oasis-new-website#63]
We should add in a link to the new OASIS SWAG store: https://www.redbubble.com/people/oasisopen/works/46186888 to the site - most likely somewhere in the 'About' section of menus.

**Comment by CarolGeyer** [comment]
CG and JH to create a CTA section for this and insert it on our STANDARDS and/or PROJECTS pages.

**Comment by chet-ensign** [comment]
Added to the bottom footer next to Member Resources. Can move elsewhere if anyone wishes. I'll close this ticket as done.
