### ISSUE TITLE
Once you are in kavi, cannot get back to public pages. When you click on OASIS logo, nothing happens.

### ISSUE THREAD

**Issue by schurbet** [oasis-dev/oasis-new-website#64]

**Comment by chet-ensign** [comment]
Confirmed. The OASIS logo from a Kavi page is not linked to anything. Your only way to return to the public pages is by typing in the www url from scratch.

**Comment by chet-ensign** [comment]
I contacted Jesse to ask if this can be made to work in Kavi.

**Comment by chet-ensign** [comment]
Checked with Jesse. He suggests opening a support ticket with Higher Logic. Will do that on Monday.

**Comment by chet-ensign** [comment]
I sent a query to support at Higher Logic: 

Is it possible to link the OASIS Open logo at the top of a Workspace back to www.oasis-open.org? 

Good morning, Stephanie, 

One of our members asked why the OASIS logo at the top of technical committee's Workspace does not link back to the main website. See, for example, https://www.oasis-open.org/apps/org/workgroup/cacao/. The OASIS logo is not linked at all.  

Is it possible to link the logo to https://www.oasis-open.org? 

Thanks for looking into this for us.

**Comment by chet-ensign** [comment]
Higher Logic issue request (181727)

**Comment by chet-ensign** [comment]
Higher Logic has updated the Kavi site so that clicking on the OASIS logo takes you to www.oasis-open.org. Test it from any internal TC page, e.g. https://www.oasis-open.org/apps/org/workgroup/mqtt/

Closing this ticket.
