### ISSUE TITLE
Legacy urls to news announcements failing

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#66]
Problem caught by former member of eTMF TC (Laurie Pattison). Links to historical news announcements about the eTMF TC are broken. See, for example, https://www.oasis-open.org/news/announcements/electronic-trial-master-file-etmf-specification-v1-0-published-by-the-etmf-tc. Changing the link to www-legacy (https://www-legacy.oasis-open.org/news/announcements/electronic-trial-master-file-etmf-specification-v1-0-published-by-the-etmf-tc) successfully retrieves the announcement. This is a 2016-era announcement. I confirmed with some other news stories. 

I will open this as a bug with HM as well.

**Comment by chet-ensign** [comment]
Opened HM issue https://github.com/humanmade/OASIS/issues/231

**Comment by chet-ensign** [comment]
I just noticed the following and added it to the HM ticket:  

Oh! Hmm. The problem doesn't appear to be that the news articles did not come over but rather than they have different URLs and the old link doesn't resolve. 

Example: I do a search in Google restricted to www.oasis-open.org/news and I find this link to the announcement of the formation of the Emergency Management TC: https://www.oasis-open.org/news/pr/oasis-members-form-emergency-management-technical-committee - clicking on that link results in Not found. 

But by paging through the articles, I find the article at https://www.oasis-open.org/2003/02/09/oasis-members-form-emergency-management-technical-committee/

**Comment by chet-ensign** [comment]
We discussed this on the sprint call w/ HM yesterday. Agreed that we'll hold the fix to a subsequent sprint.

**Comment by chet-ensign** [comment]
Fixed on staging but not pushed to production. We'll take back up when maintenance starts in April.

**Comment by OASIS-OP-Admin** [comment]
The fix was pushed to production by HM. Checking over a number of the TC web pages didn't turn up any broken links. It looks to be working correctly, so I will close the ticket.
