### ISSUE TITLE
Check formatting for all documents on the Policies page 

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#70]
Noted random layout problems while fixing ToCs. All policy docs should be reviewed and, where needed, cleaned up.

**Comment by OASIS-OP-Admin** [comment]
Checked all policy pages. All appear to be formatted properly with the possible exception that numbered lists all use numerals where we originally used a mix of numbers and letters. That's not a show stopper. I will close this ticket and open a ticket to HM to see if we can get other numbered list options added.

**Comment by chet-ensign** [comment]
Opened HM ticket https://github.com/humanmade/OASIS/issues/262 to ask about getting alpha-style lists working.
