### ISSUE TITLE
Link for mail list archive help broken; needs to be directed to "legacy"

### ISSUE THREAD

**Issue by paul-knight** [oasis-dev/oasis-new-website#78]
Maybe this can be combined with another issue...

In the email list archives, there is a link to "OASIS Mailing List Help" which is hyperlinked to:
- http://www.oasis-open.org/maillists/guidelines.php#searchingarchives

It will work if it is redirected to:
- http://www-legacy.oasis-open.org/maillists/guidelines.php#searchingarchives

**Comment by OASIS-OP-Admin** [comment]
Sent email to Jesse - 

Fix broken link on lists archive page 

Hi Jesse, 

I'm tackling some of the open tickets for the new website. 

On the OASIS Mailing List Directory page (https://lists.oasis-open.org/archives/), under Related links, the link to Mailing List Guidelines and Procedures is broken. It tries to link to https://www.oasis-open.org/maillists/guidelines.php.

Can you link it to https://www.oasis-open.org/policies-guidelines/mailing-lists/ instead?

**Comment by OASIS-OP-Admin** [comment]
Realized this ticket is for individual email archives. Followed up with 2nd email to Jesse 

Hi Jesse, 

I just realized that Paul was also pointing out that the links on the individual archive pages is broken. For example, on https://lists.oasis-open.org/archives/members/, in the yellow box, OASIS Mailing Lists Help is also broken, pointing to http://www.oasis-open.org/maillists/guidelines.php#searchingarchives

Can you change those to point to https://www.oasis-open.org/policies-guidelines/mailing-lists/#searchingarchives ?

Thanks, 

/chet

**Comment by OASIS-OP-Admin** [comment]
Jesse added a redirect to handle the link. It works, including the # suffix. 

I'll close this ticket.
