### ISSUE TITLE
Adjust/replace photos for Board, staff pages

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#79]
Not a priority, but we do need to clean up these photo pages so photos are clear and more uniform in appearance. We don't need to have the same backgrounds, but faces should be the same relative sizes.

**Comment by chet-ensign** [comment]
Hi @mbminto - I'm looking through the tickets underway. Did you know about this one being assigned to you. I don't recall how that came about.

**Comment by CarolGeyer** [comment]
Before MB spends any more time looking for better photos and cropping the ones we have, Chet will see if HM can provide a more fool-proof solution to adding photos. Is there a different plugin or design?

**Comment by chet-ensign** [comment]
We discussed this today. I have opened https://github.com/humanmade/OASIS/issues/261 to ask HM to look into or suggest plugins that might help with the pictures.

**Comment by OASIS-OP-Admin** [comment]
I reviewed the photos for board, staff, distinguished contributors and op advisory council. The portraits look pretty good. Some of the DCs could be better but, with the source we have, they're probably about the best that can be expected. 

I'll close this ticket.
