### ISSUE TITLE
Open Projects page with Active filter applied by default

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#8]
Issue identified by @CarolGeyer. 

Goal: as a visitor to the OASIS web site, when I open the list of projects, I only want to see those that are currently active. If I want to see inactive ones, I'll select that option. 

Currently the site shows all projects, most of which are closed.

**Comment by chet-ensign** [comment]
Opened this on the HM issues list in https://github.com/humanmade/OASIS/issues/221

**Comment by chet-ensign** [comment]
Than provided a method for us to make the change: 

Yup! On the Appearance > Menus screen here, just create a new "Custom Link" with the URL "/projects-committees/?filter-committee-status=active" and the Link text "Projects & Committees". Then drag it into the place where the existing "Projects & Committees" menu item is, and remove the old one.

This link will apply the active filter automatically. I don't have access to menus so I asked Scott to make the update.

**Comment by chet-ensign** [comment]
I made the edit to the 'View all projects' button on the home page and now that one works.

**Comment by CarolGeyer** [comment]
Chet's fix works perfectly. Now we need to implement it on the 'View all Projects' page that links from the top and footer navs.

**Comment by chet-ensign** [comment]
This issue is complete and can be closed.
