### ISSUE TITLE
Revise and update Distinguished Contributors page

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#80]
The order the photos are displaying in isn't clear--it's not alpha.

That said, alpha may not make sense now that we have so many DCs. We should consider the best way to display--perhaps the most recent year's inductees first, then an alpha list of the others?

Also, many of the DC's bios are out-of-date. We may want to remove the bios altogether (people change jobs so frequently) and instead link to each person's LinkedIn profile.

**Comment by chet-ensign** [comment]
I like the idea of linking previous year's winners to LI where possible. That's a great way to keep them refreshed. Or at least give the sense that they are. Also, some people might want to connect with them and that'd b a good pathway.

**Comment by CarolGeyer** [comment]
Here's my proposal:

[ ]  Chet asks HM to fix the DC page so the bios display in alpha order by last name. (that's a bug)

[ ] Whenever Mary Beth has time, she starts editing the bios of each DC to a) remove their Job titles (so only their names will appear on the main page) and b) retain the first sentence of their bios (which says the year they were inducted) and replace the rest with a link to the person's LinkedIn profile. (It's a shame to lose some of the profile text, but it's impossible to keep it up-to-date as the years go by.)

[ ] After the Awards Ceremony next month, Carol adds a sentence to the top paragraph of the main DC page that calls out the names of the DCs inducted in the last year. Their names will be linked to their profiles on our site. In future years, Mary Beth will edit that sentence when new inductees are named.

Make sense?

**Comment by chet-ensign** [comment]
This sounds good to me.

**Comment by mbminto** [comment]
Updated the DC page and have a couple of things:
- Bosak isn't on LI (that I could find...) I left his profile to only say the year that he was named DC. 
- Lockhart - when was he named DC? I don't see anything on our website; his LI profile says DC but doesn't say the year.

**Comment by chet-ensign** [comment]
Also, looks like the photo for Bill Cox is lost. @mbminto - I found it. https://www.oasis-open.org/wp-admin/upload.php?item=5201 - William Cox, Ph.D.

**Comment by mbminto** [comment]
> Also, looks like the photo for Bill Cox is lost. @mbminto - I found it. https://www.oasis-open.org/wp-admin/upload.php?item=5201 - William Cox, Ph.D.

Thanks! Just updated the page w/ his photo.

**Comment by CarolGeyer** [comment]
MB did a great job with all these DCs!

I added a sentence to the top to call out the most recent inductees with a link to the press release.

I think the only action remaining is for Chet to get HM to figure out why the  first seven DCs aren't displaying in alpha order.

**Comment by chet-ensign** [comment]
Fixed. Looking at the entries, I found the first 7 had their order field set to -9. That was lifting them ahead of the others. I set them back to 0. Now, all DCs are in alphabetical order. (Well, William Cox is before Tony Cox but I think we can live with that.)
