### ISSUE TITLE
Where is the link to 'set up username and password' for a new member on new website

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#84]
Raised by @schurbet: 

"Where is the 'set up username and password' link on new website? - for an individual from a member company that has never set up UN and PW before. That used to be an option from join menu

**Comment by scottmcgrath** [comment]
The problem with solving this - there are several meanings to "user"  IF the question is "Where do I send someone who 1. is an employee of an existing member  and 2. wants to create an account in kavi for TC related activities?"  Same as always: https://www.oasis-open.org/kmembership_info/person_signup  One would find that link after starting at the link "TC Workspace login" which takes you to the kavi login -- which if you do no have credentials, offers the opportunity to create them.

**Comment by chet-ensign** [comment]
We discussed this today. @scottmcgrath noted that we do need to do a better job of explaining / naming the two login links at the top of the page. Leaving on the To do column for now.

**Comment by chet-ensign** [comment]
Scott added 'Member Login Tips' to the top right, next to the logins. That seems to address the problem. Closing this ticket.
