### ISSUE TITLE
Configure the SEO and Sharethis plugins 

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#85]
Now that Yoast, the SEO plugin, is installed, we need to learn how to use it and start configuring it to put it to work.

**Comment by scottmcgrath** [comment]
ShareThis is configured to appear at top of posts

**Comment by chet-ensign** [comment]
Looks great.

**Comment by scottmcgrath** [comment]
SEO config for Yoast is done
