### ISSUE TITLE
Make editorial updates to the CLA forms and descriptions

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#89]
Raised by @CarolGeyer and @jamienewlaw 

The acronyms, 'I-CLA' and 'E-CLA', aren't used in the OP Rules doc. Consequently, the page doesn't appear in searches on those terms. @ChetEiii @Jamie --can we insert the acronyms in the OP Rules without asking for Board review/approval?

before we touch those texts, we should probably briefly look in with @scott-mcgrath  to the ongoing Drupal>WP CLA adaptations ... better to gather up the typos and form adjustments, and then report to the Board that we've slightly cleaned up the text once, than three times in a row

we need to close on the ECLA text for the Open Repo program.

**Comment by chet-ensign** [comment]
We discussed this today. This is a CLA project issue, not a website issue. I'll move it off the project board.

**Comment by OASIS-OP-Admin** [comment]
Per the decision I documented above, and the progress underway for CLAs, I am closing this ticket.
