### ISSUE TITLE
Ask HM for enhancements to design options for tables

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#92]

**Comment by CarolGeyer** [comment]
How can we adjust tables so they don't span the full page width?

Example: we have two tables on https://www.oasis-open.org/join-3/ ; the bottom table (Open Project Dues) especially looks too wide. Would prefer to have the table match the paragraph width.

When in Edit mode, I can set the table alignment to be centered, which appears to do what we want, but when I Update the page, it defaults back to full width.

**Comment by chet-ensign** [comment]
I learned a trick today. Not that this will be everybody's groove, but you can directly edit the tables in HTML. I copied the HTML code for the tables laying out roles for TC and OP members and pasted it into the Committee Operations document in HTML mode. Both tables had failed to come over and this was a quick, easy fix. We can probably do table enhancements this way if we want.

**Comment by OASIS-OP-Admin** [comment]
@CarolGeyer clarifies the immediate need: We have an immediate need to get the tables to adjust the width of tables, so they match the body text and not appear at full page width. This is an issue on https://www.oasis-open.org/join-3/ and https://www.oasis-open.org/foundation-as-a-service/

**Comment by OASIS-OP-Admin** [comment]
This issue incorporates #46. I opened https://app.zenhub.com/workspaces/oasis-design--build-5f1f650945622c000fb4d09c/issues/humanmade/oasis/247 to bring this up with HM.

**Comment by chet-ensign** [comment]
HM issue #247 - Create tables that fit into the width of the text column, not the full width of the page - has been entered and is top priority for the next sprint. i will mark this issue as closed since work is underway.
