### ISSUE TITLE
Display list of terms in OASIS Defined Terms using alphabetic characters, not numbers

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#94]
Defined Terms were previously listed in alphabetic order (a, b, c, aa, ab, ac). To maintain continuity, redefine the current style to be alphabetic.

**Comment by chet-ensign** [comment]
Setting the list to <ol type="a"> does not change the appearance. Presumably overridden by the style sheet.

**Comment by OASIS-OP-Admin** [comment]
HumanMade updated the style sheet. It now respects the HTML order attribute on lists. This is now working as expected so I'll close the ticket.
